import { Icon } from "./Icon";
import { categoryFilters } from "./sampleData";
import type { Conversation, ConversationCategory, StatusFilter } from "./types";

type ConversationListProps = {
  conversations: Conversation[]; selectedId: string; search: string; category: ConversationCategory; status: StatusFilter;
  onSearchChange: (value: string) => void; onCategoryChange: (value: ConversationCategory) => void; onStatusChange: (value: StatusFilter) => void; onSelect: (id: string) => void;
};
const statusDot: Record<Conversation["status"], string> = { 対応中: "bg-amber-400", 未対応: "bg-rose-500", 解決済み: "bg-emerald-500" };

export function ConversationList({ conversations, selectedId, search, category, status, onSearchChange, onCategoryChange, onStatusChange, onSelect }: ConversationListProps) {
  return <aside className="flex min-h-0 w-full flex-col border-r border-slate-200 bg-white lg:w-[342px] lg:shrink-0">
    <div className="border-b border-slate-100 px-5 pb-4 pt-5">
      <div className="mb-4"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">Inbox</p><h2 className="mt-1 text-lg font-semibold tracking-[-0.02em] text-slate-900">問い合わせ一覧</h2></div>
      <label className="relative block"><span className="sr-only">問い合わせを検索</span><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="名前、件名、内容で検索" className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-10 pr-3 text-[13px] text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-blue-400 focus:bg-white focus:ring-2 focus:ring-blue-100" /><span className="pointer-events-none absolute left-3 top-[11px] text-slate-400"><Icon name="search" size={17} /></span></label>
      <div className="mt-4 flex items-center gap-1 overflow-x-auto pb-0.5">{(["すべて", "未対応", "対応中", "解決済み"] as const).map((filter) => <button key={filter} onClick={() => onStatusChange(filter)} className={`whitespace-nowrap rounded-md px-2.5 py-1.5 text-[11px] font-medium transition ${status === filter ? "bg-slate-900 text-white" : "text-slate-500 hover:bg-slate-100"}`}>{filter}</button>)}</div>
    </div>
    <div className="min-h-0 flex-1 overflow-y-auto"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-3 text-[11px] text-slate-400"><span>{conversations.length} 件の問い合わせ</span><select value={category} onChange={(event) => onCategoryChange(event.target.value as ConversationCategory)} className="max-w-[130px] cursor-pointer bg-transparent text-right font-medium text-slate-500 outline-none"><option value="すべて">カテゴリ：すべて</option>{categoryFilters.slice(1).map((filter) => <option key={filter.label} value={filter.label}>{filter.label}（{filter.count}）</option>)}</select></div>
      {conversations.length === 0 ? <div className="px-6 py-12 text-center text-sm text-slate-400">該当する問い合わせがありません</div> : conversations.map((conversation) => <button key={conversation.id} onClick={() => onSelect(conversation.id)} className={`group block w-full border-b border-slate-100 px-5 py-4 text-left transition ${selectedId === conversation.id ? "bg-blue-50/70" : "hover:bg-slate-50"}`}><div className="flex items-start gap-3"><div className={`relative flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[11px] font-semibold ${selectedId === conversation.id ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{conversation.initials}<span className={`absolute -bottom-0.5 -right-0.5 h-2.5 w-2.5 rounded-full border-2 border-white ${statusDot[conversation.status]}`} /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className={`truncate text-[13px] font-semibold ${selectedId === conversation.id ? "text-blue-950" : "text-slate-800"}`}>{conversation.customerName}</p><span className="shrink-0 text-[10px] text-slate-400">{conversation.updatedAt}</span></div><p className="mt-1 truncate text-[12px] font-medium text-slate-600">{conversation.subject}</p><p className="mt-1 truncate text-[11px] leading-5 text-slate-400">{conversation.preview}</p><div className="mt-2 flex items-center gap-2"><span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">{conversation.category}</span>{conversation.priority === "高" && <span className="flex items-center gap-1 text-[10px] font-medium text-rose-500"><Icon name="warning" size={11} />優先</span>}</div></div></div></button>)}</div>
  </aside>;
}
