import { Icon } from "./Icon";
import { ReplyComposer } from "./ReplyComposer";
import type { Conversation } from "./types";

type ConversationDetailProps = { conversation: Conversation; showEscalation: boolean; onCloseEscalation: () => void; onResolve: () => void; onEscalate: () => void; onSend: (body: string) => void };

export function ConversationDetail({ conversation, showEscalation, onCloseEscalation, onResolve, onEscalate, onSend }: ConversationDetailProps) {
  return <section className="flex min-h-[680px] min-w-0 flex-1 flex-col bg-[#f8fafc]"><header className="flex min-h-[84px] items-center justify-between gap-4 border-b border-slate-200 bg-white px-6 py-4 xl:px-8"><div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-blue-100 text-sm font-semibold text-blue-700">{conversation.initials}</div><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-base font-semibold text-slate-900">{conversation.customerName}</h1><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /><span className="text-[11px] text-emerald-600">オンライン</span></div><p className="mt-1 truncate text-xs text-slate-400">{conversation.email} <span className="mx-1.5 text-slate-300">·</span> 最終更新 {conversation.updatedAt}</p></div></div><div className="flex shrink-0 items-center gap-2"><button onClick={onResolve} className="hidden items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-600 transition hover:border-emerald-200 hover:bg-emerald-50 hover:text-emerald-700 sm:flex"><Icon name="check" size={14} />解決済みにする</button><button className="rounded-lg border border-slate-200 p-2 text-slate-500 transition hover:bg-slate-50" aria-label="問い合わせのその他メニュー"><Icon name="more" size={17} /></button></div></header>
    {showEscalation && <div className="flex items-center justify-between border-b border-amber-200 bg-amber-50 px-6 py-3 xl:px-8"><div className="flex items-center gap-2.5"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-amber-600"><Icon name="warning" size={15} /></span><div><p className="text-xs font-semibold text-amber-900">エスカレーション候補</p><p className="mt-0.5 text-[11px] text-amber-700">配送遅延に関する問い合わせです。必要に応じて配送チームへ引き継いでください。</p></div></div><div className="flex items-center gap-3"><button onClick={onEscalate} className="whitespace-nowrap rounded-md bg-amber-500 px-3 py-1.5 text-[11px] font-semibold text-white shadow-sm shadow-amber-200 transition hover:bg-amber-600">引き継ぐ</button><button onClick={onCloseEscalation} className="text-amber-500 transition hover:text-amber-800" aria-label="エスカレーション表示を閉じる"><Icon name="close" size={15} /></button></div></div>}
    <div className="min-h-0 flex-1 overflow-y-auto px-6 py-7 xl:px-16"><div className="mx-auto max-w-3xl"><div className="mb-7 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200" /><span className="rounded-full bg-slate-200/70 px-3 py-1 text-[10px] font-medium text-slate-500">今日</span><div className="h-px flex-1 bg-slate-200" /></div><div className="space-y-6">{conversation.messages.map((message) => { if (message.sender === "system") return <div key={message.id} className="text-center text-[11px] text-slate-400">{message.body}</div>; const isOperator = message.sender === "operator"; return <div key={message.id} className={`flex items-end gap-2.5 ${isOperator ? "justify-end" : "justify-start"}`}>{!isOperator && <div className="mb-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-100 text-[9px] font-semibold text-blue-700">{conversation.initials}</div>}<div className={`max-w-[min(78%,520px)] ${isOperator ? "items-end" : "items-start"} flex flex-col`}><div className={`rounded-2xl px-4 py-3 text-[13px] leading-6 shadow-sm ${isOperator ? "rounded-br-md bg-blue-600 text-white" : "rounded-bl-md border border-slate-200 bg-white text-slate-700"}`}><p>{message.body}</p>{message.attachment && <div className={`mt-3 flex items-center gap-2 rounded-lg px-2.5 py-2 text-[11px] ${isOperator ? "bg-blue-500 text-blue-50" : "bg-slate-50 text-slate-600"}`}><Icon name="paperclip" size={14} />{message.attachment}<Icon name="external" size={13} /></div>}</div><span className="mt-1.5 px-1 text-[10px] text-slate-400">{isOperator ? "あなた" : conversation.customerName} · {message.time}</span></div>{isOperator && <div className="mb-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-slate-900 text-[9px] font-semibold text-white">OP</div>}</div>; })}</div><div className="my-8 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200" /><span className="text-[10px] text-slate-400">返信を入力してください</span><div className="h-px flex-1 bg-slate-200" /></div><ReplyComposer onSend={onSend} /></div></div>
  </section>;
}
